package com.smartq.api.auth.domain;

public enum UserPermission {
    BOOK_APPOINTMENT,
    MANAGE_OWN_APPOINTMENTS,
    VIEW_OWN_QUEUE_STATUS,
    VIEW_ASSIGNED_APPOINTMENTS,
    MANAGE_QUEUE,
    UPDATE_APPOINTMENT_STATUS,
    VIEW_BRANCH_WORKLOAD,
    MANAGE_BRANCHES,
    MANAGE_SERVICES,
    MANAGE_STAFF,
    VIEW_ANALYTICS,
    VIEW_REPORTS,
    MANAGE_APPOINTMENTS
}
